build only N packages at once

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -3,14 +3,14 @@
 set -e
 
 PROJECT_ROOT=$(cd $(dirname $0)/.. && pwd)
-FAIL=0
+N=4
 
 echo -e "🦘🦘🦘 BUILDING GROUPAROO MONOREPO 🦘🦘"
 echo -e "dir: $PROJECT_ROOT"
 echo -e ""
 
 # 0. build dependancies
-echo "--- (re)building dependancies in parallel ---"
+echo "--- (re)building npm dependancies in parallel ---"
 DEPS=""
 for p in $PROJECT_ROOT/node_modules/**/package.json ; do
   # matching "install" will find both postinstall and install scripts!
@@ -22,28 +22,32 @@ echo "$DEPS"
 npm rebuild $DEPS
 echo -e  "\r\n✨ npm rebuild complete\r\n"
 
-# 1. build core/api
+# # 1. build core/api
 echo "--- building core/api ---"
 cd $PROJECT_ROOT/core/api
 npm run build-api
 echo -e "\r\n✨ core API compiled from typescript\r\n"
 
 # 2. build plugins
-echo "--- building plugins in parallel ---"
+echo "--- building plugins in parallel (parallelism of $N) ---"
+
+count=0
 for d in $PROJECT_ROOT/plugins/*/* ; do
-    (cd "$d" && npm run prepare) &
+  echo -e "    -> $d"
+  output=$(cd "$d" && npm run prepare) &
+  pid=$!
+  let count+=1
+  [[ $((count%N)) -eq 0 ]] && wait "$pid"
 done
-for job in `jobs -p`
-do
-    wait $job || let "FAIL+=1"
-done
-if [ "$FAIL" == "0" ];
-then
-    echo -e "\r\n✨ all plugins built\r\n"
-else
-    echo -e "\r\n❗️ error building plugins\r\n"
+
+for job in `jobs -p`; do
+  wait $job || (
+    echo -e "\r\n❗️ error building plugins\r\n" &&
     exit 1
-fi
+  )
+done
+
+echo -e "\r\n✨ all plugins built\r\n"
 
 # 3. build main app
 echo "--- building the main app ---"
