Abort publish if no dist folder (#2281)
* Check for core/dist in publish

* Better dist checking

* Better plugin dist checking, removing testing code

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -124,6 +124,22 @@ rm -rf ui/*/.next
 pnpm install --prefer-frozen-lockfile
 git checkout pnpm-lock.yaml # the other github action will take care of this, but we need a clean working directory to publish
 
+# Check to make sure it was built correctly
+
+PLUGINS=`find 'plugins' -name src -and -type d | wc -l`
+BUILT_PLUGINS=`find 'plugins' -name dist -and -type d | wc -l`
+
+if [ ! -d "core/dist" ] ||\
+   [ ! -d "cli/dist" ] ||\
+   [ ! -d "ui/ui-community/.next" ] ||\
+   [ ! -d "ui/ui-config/.next" ] ||\
+   [ ! -d "ui/ui-enterprise/.next" ] ||\
+   [ "$PLUGINS" != "$BUILT_PLUGINS" ]; then
+  echo "Missing dist folder(s), exiting"
+  exit 1
+fi
+
+
 echo ""
 echo "-----> PUSH TO NPM"
 echo ""
